languages:
   JavaScript: true

engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true

ratings:
  paths:
  - src/**
  - test/**
  - tasks/**

exclude_paths:
- "build/"
- "benchmark/"
- "external/"
- "**.d.ts"