languages:
   JavaScript: true

engines:
  eslint:
    enabled: true
  duplication:
    enabled: true

ratings:
  paths:
  - src/**
  - tasks/**

exclude_paths:
- "build/"
- "test/"
- "test/unit/"
- "benchmark/"
- "external/"
- "**.d.ts"