language: node_js
node_js:
  - "node"
  - "0.12"
  - "0.10"
sudo: false

install:
  - pip install coveralls

before_script:
  - npm install -g grunt-cli

script: 
  - grunt build:travis
  - coverage run nyc npm test && nyc report
  - coveralls run nyc npm test && nyc report --reporter=text-lcov

after_success: coveralls