language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

# using container-based infrastructure
sudo: false

# clone repositories to a depth of 10 commits
git:
  depth: 10

before_script:
  - npm install -g grunt-cli

script: grunt build:travis

after_success: npm run coveralls