language: node_js
node_js:
  - "node"
  - "4"
  - "0.12"
  - "0.10"

# using container-based infrastructure
sudo: false

# clone repositories to a depth of 10 commits
git:
  depth: 10

cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - npm install -g grunt-cli

script: 
  - grunt build:travis

after_success: 
  - npm run coveralls

addons:
    code_climate:
        repo_token: f0d18567cc2d330035c98da79e86a314a33ab95c781ba14f382e5408acaba0ca